/* This file is automatically generated based on your hardware design. */
#include "memory_config.h"

struct memory_range_s memory_ranges[] = {
	/* dlmb_cntlr memory will not be tested since application resides in the same memory */
	{
		"ddr_sdram",
		"mpmc",
		0x8c000000,
		67108864,
	},
};

int n_memory_ranges = 1;
